# Generated by Django 2.0.5 on 2018-06-03 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blogposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
